package types

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *PendingReward) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Address":
			err = dc.ReadExactBytes((z.Address)[:])
			if err != nil {
				err = msgp.WrapError(err, "Address")
				return
			}
		case "EpochNum":
			z.EpochNum, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "EpochNum")
				return
			}
		case "Amount":
			err = dc.ReadExactBytes((z.Amount)[:])
			if err != nil {
				err = msgp.WrapError(err, "Amount")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *PendingReward) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "Address"
	err = en.Append(0x83, 0xa7, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73)
	if err != nil {
		return
	}
	err = en.WriteBytes((z.Address)[:])
	if err != nil {
		err = msgp.WrapError(err, "Address")
		return
	}
	// write "EpochNum"
	err = en.Append(0xa8, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x4e, 0x75, 0x6d)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.EpochNum)
	if err != nil {
		err = msgp.WrapError(err, "EpochNum")
		return
	}
	// write "Amount"
	err = en.Append(0xa6, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74)
	if err != nil {
		return
	}
	err = en.WriteBytes((z.Amount)[:])
	if err != nil {
		err = msgp.WrapError(err, "Amount")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *PendingReward) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "Address"
	o = append(o, 0x83, 0xa7, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73)
	o = msgp.AppendBytes(o, (z.Address)[:])
	// string "EpochNum"
	o = append(o, 0xa8, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x4e, 0x75, 0x6d)
	o = msgp.AppendInt64(o, z.EpochNum)
	// string "Amount"
	o = append(o, 0xa6, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74)
	o = msgp.AppendBytes(o, (z.Amount)[:])
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *PendingReward) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Address":
			bts, err = msgp.ReadExactBytes(bts, (z.Address)[:])
			if err != nil {
				err = msgp.WrapError(err, "Address")
				return
			}
		case "EpochNum":
			z.EpochNum, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "EpochNum")
				return
			}
		case "Amount":
			bts, err = msgp.ReadExactBytes(bts, (z.Amount)[:])
			if err != nil {
				err = msgp.WrapError(err, "Amount")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *PendingReward) Msgsize() (s int) {
	s = 1 + 8 + msgp.ArrayHeaderSize + (20 * (msgp.ByteSize)) + 9 + msgp.Int64Size + 7 + msgp.ArrayHeaderSize + (32 * (msgp.ByteSize))
	return
}

// DecodeMsg implements msgp.Decodable
func (z *StakingInfo) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "CurrEpochNum":
			z.CurrEpochNum, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "CurrEpochNum")
				return
			}
		case "Validators":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Validators")
				return
			}
			if cap(z.Validators) >= int(zb0002) {
				z.Validators = (z.Validators)[:zb0002]
			} else {
				z.Validators = make([]*Validator, zb0002)
			}
			for za0001 := range z.Validators {
				if dc.IsNil() {
					err = dc.ReadNil()
					if err != nil {
						err = msgp.WrapError(err, "Validators", za0001)
						return
					}
					z.Validators[za0001] = nil
				} else {
					if z.Validators[za0001] == nil {
						z.Validators[za0001] = new(Validator)
					}
					err = z.Validators[za0001].DecodeMsg(dc)
					if err != nil {
						err = msgp.WrapError(err, "Validators", za0001)
						return
					}
				}
			}
		case "PendingRewards":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "PendingRewards")
				return
			}
			if cap(z.PendingRewards) >= int(zb0003) {
				z.PendingRewards = (z.PendingRewards)[:zb0003]
			} else {
				z.PendingRewards = make([]*PendingReward, zb0003)
			}
			for za0002 := range z.PendingRewards {
				if dc.IsNil() {
					err = dc.ReadNil()
					if err != nil {
						err = msgp.WrapError(err, "PendingRewards", za0002)
						return
					}
					z.PendingRewards[za0002] = nil
				} else {
					if z.PendingRewards[za0002] == nil {
						z.PendingRewards[za0002] = new(PendingReward)
					}
					err = z.PendingRewards[za0002].DecodeMsg(dc)
					if err != nil {
						err = msgp.WrapError(err, "PendingRewards", za0002)
						return
					}
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *StakingInfo) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "CurrEpochNum"
	err = en.Append(0x83, 0xac, 0x43, 0x75, 0x72, 0x72, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x4e, 0x75, 0x6d)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.CurrEpochNum)
	if err != nil {
		err = msgp.WrapError(err, "CurrEpochNum")
		return
	}
	// write "Validators"
	err = en.Append(0xaa, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Validators)))
	if err != nil {
		err = msgp.WrapError(err, "Validators")
		return
	}
	for za0001 := range z.Validators {
		if z.Validators[za0001] == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			err = z.Validators[za0001].EncodeMsg(en)
			if err != nil {
				err = msgp.WrapError(err, "Validators", za0001)
				return
			}
		}
	}
	// write "PendingRewards"
	err = en.Append(0xae, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.PendingRewards)))
	if err != nil {
		err = msgp.WrapError(err, "PendingRewards")
		return
	}
	for za0002 := range z.PendingRewards {
		if z.PendingRewards[za0002] == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			err = z.PendingRewards[za0002].EncodeMsg(en)
			if err != nil {
				err = msgp.WrapError(err, "PendingRewards", za0002)
				return
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *StakingInfo) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "CurrEpochNum"
	o = append(o, 0x83, 0xac, 0x43, 0x75, 0x72, 0x72, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x4e, 0x75, 0x6d)
	o = msgp.AppendInt64(o, z.CurrEpochNum)
	// string "Validators"
	o = append(o, 0xaa, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Validators)))
	for za0001 := range z.Validators {
		if z.Validators[za0001] == nil {
			o = msgp.AppendNil(o)
		} else {
			o, err = z.Validators[za0001].MarshalMsg(o)
			if err != nil {
				err = msgp.WrapError(err, "Validators", za0001)
				return
			}
		}
	}
	// string "PendingRewards"
	o = append(o, 0xae, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.PendingRewards)))
	for za0002 := range z.PendingRewards {
		if z.PendingRewards[za0002] == nil {
			o = msgp.AppendNil(o)
		} else {
			o, err = z.PendingRewards[za0002].MarshalMsg(o)
			if err != nil {
				err = msgp.WrapError(err, "PendingRewards", za0002)
				return
			}
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *StakingInfo) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "CurrEpochNum":
			z.CurrEpochNum, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CurrEpochNum")
				return
			}
		case "Validators":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Validators")
				return
			}
			if cap(z.Validators) >= int(zb0002) {
				z.Validators = (z.Validators)[:zb0002]
			} else {
				z.Validators = make([]*Validator, zb0002)
			}
			for za0001 := range z.Validators {
				if msgp.IsNil(bts) {
					bts, err = msgp.ReadNilBytes(bts)
					if err != nil {
						return
					}
					z.Validators[za0001] = nil
				} else {
					if z.Validators[za0001] == nil {
						z.Validators[za0001] = new(Validator)
					}
					bts, err = z.Validators[za0001].UnmarshalMsg(bts)
					if err != nil {
						err = msgp.WrapError(err, "Validators", za0001)
						return
					}
				}
			}
		case "PendingRewards":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PendingRewards")
				return
			}
			if cap(z.PendingRewards) >= int(zb0003) {
				z.PendingRewards = (z.PendingRewards)[:zb0003]
			} else {
				z.PendingRewards = make([]*PendingReward, zb0003)
			}
			for za0002 := range z.PendingRewards {
				if msgp.IsNil(bts) {
					bts, err = msgp.ReadNilBytes(bts)
					if err != nil {
						return
					}
					z.PendingRewards[za0002] = nil
				} else {
					if z.PendingRewards[za0002] == nil {
						z.PendingRewards[za0002] = new(PendingReward)
					}
					bts, err = z.PendingRewards[za0002].UnmarshalMsg(bts)
					if err != nil {
						err = msgp.WrapError(err, "PendingRewards", za0002)
						return
					}
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *StakingInfo) Msgsize() (s int) {
	s = 1 + 13 + msgp.Int64Size + 11 + msgp.ArrayHeaderSize
	for za0001 := range z.Validators {
		if z.Validators[za0001] == nil {
			s += msgp.NilSize
		} else {
			s += z.Validators[za0001].Msgsize()
		}
	}
	s += 15 + msgp.ArrayHeaderSize
	for za0002 := range z.PendingRewards {
		if z.PendingRewards[za0002] == nil {
			s += msgp.NilSize
		} else {
			s += z.PendingRewards[za0002].Msgsize()
		}
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Validator) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Address":
			err = dc.ReadExactBytes((z.Address)[:])
			if err != nil {
				err = msgp.WrapError(err, "Address")
				return
			}
		case "Pubkey":
			err = dc.ReadExactBytes((z.Pubkey)[:])
			if err != nil {
				err = msgp.WrapError(err, "Pubkey")
				return
			}
		case "RewardTo":
			err = dc.ReadExactBytes((z.RewardTo)[:])
			if err != nil {
				err = msgp.WrapError(err, "RewardTo")
				return
			}
		case "VotingPower":
			z.VotingPower, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "VotingPower")
				return
			}
		case "Introduction":
			z.Introduction, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Introduction")
				return
			}
		case "StakedCoins":
			err = dc.ReadExactBytes((z.StakedCoins)[:])
			if err != nil {
				err = msgp.WrapError(err, "StakedCoins")
				return
			}
		case "IsUnbonding":
			z.IsUnbonding, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "IsUnbonding")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Validator) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 7
	// write "Address"
	err = en.Append(0x87, 0xa7, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73)
	if err != nil {
		return
	}
	err = en.WriteBytes((z.Address)[:])
	if err != nil {
		err = msgp.WrapError(err, "Address")
		return
	}
	// write "Pubkey"
	err = en.Append(0xa6, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79)
	if err != nil {
		return
	}
	err = en.WriteBytes((z.Pubkey)[:])
	if err != nil {
		err = msgp.WrapError(err, "Pubkey")
		return
	}
	// write "RewardTo"
	err = en.Append(0xa8, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x54, 0x6f)
	if err != nil {
		return
	}
	err = en.WriteBytes((z.RewardTo)[:])
	if err != nil {
		err = msgp.WrapError(err, "RewardTo")
		return
	}
	// write "VotingPower"
	err = en.Append(0xab, 0x56, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x77, 0x65, 0x72)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.VotingPower)
	if err != nil {
		err = msgp.WrapError(err, "VotingPower")
		return
	}
	// write "Introduction"
	err = en.Append(0xac, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteString(z.Introduction)
	if err != nil {
		err = msgp.WrapError(err, "Introduction")
		return
	}
	// write "StakedCoins"
	err = en.Append(0xab, 0x53, 0x74, 0x61, 0x6b, 0x65, 0x64, 0x43, 0x6f, 0x69, 0x6e, 0x73)
	if err != nil {
		return
	}
	err = en.WriteBytes((z.StakedCoins)[:])
	if err != nil {
		err = msgp.WrapError(err, "StakedCoins")
		return
	}
	// write "IsUnbonding"
	err = en.Append(0xab, 0x49, 0x73, 0x55, 0x6e, 0x62, 0x6f, 0x6e, 0x64, 0x69, 0x6e, 0x67)
	if err != nil {
		return
	}
	err = en.WriteBool(z.IsUnbonding)
	if err != nil {
		err = msgp.WrapError(err, "IsUnbonding")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Validator) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 7
	// string "Address"
	o = append(o, 0x87, 0xa7, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73)
	o = msgp.AppendBytes(o, (z.Address)[:])
	// string "Pubkey"
	o = append(o, 0xa6, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79)
	o = msgp.AppendBytes(o, (z.Pubkey)[:])
	// string "RewardTo"
	o = append(o, 0xa8, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x54, 0x6f)
	o = msgp.AppendBytes(o, (z.RewardTo)[:])
	// string "VotingPower"
	o = append(o, 0xab, 0x56, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x77, 0x65, 0x72)
	o = msgp.AppendInt64(o, z.VotingPower)
	// string "Introduction"
	o = append(o, 0xac, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e)
	o = msgp.AppendString(o, z.Introduction)
	// string "StakedCoins"
	o = append(o, 0xab, 0x53, 0x74, 0x61, 0x6b, 0x65, 0x64, 0x43, 0x6f, 0x69, 0x6e, 0x73)
	o = msgp.AppendBytes(o, (z.StakedCoins)[:])
	// string "IsUnbonding"
	o = append(o, 0xab, 0x49, 0x73, 0x55, 0x6e, 0x62, 0x6f, 0x6e, 0x64, 0x69, 0x6e, 0x67)
	o = msgp.AppendBool(o, z.IsUnbonding)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Validator) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Address":
			bts, err = msgp.ReadExactBytes(bts, (z.Address)[:])
			if err != nil {
				err = msgp.WrapError(err, "Address")
				return
			}
		case "Pubkey":
			bts, err = msgp.ReadExactBytes(bts, (z.Pubkey)[:])
			if err != nil {
				err = msgp.WrapError(err, "Pubkey")
				return
			}
		case "RewardTo":
			bts, err = msgp.ReadExactBytes(bts, (z.RewardTo)[:])
			if err != nil {
				err = msgp.WrapError(err, "RewardTo")
				return
			}
		case "VotingPower":
			z.VotingPower, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "VotingPower")
				return
			}
		case "Introduction":
			z.Introduction, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Introduction")
				return
			}
		case "StakedCoins":
			bts, err = msgp.ReadExactBytes(bts, (z.StakedCoins)[:])
			if err != nil {
				err = msgp.WrapError(err, "StakedCoins")
				return
			}
		case "IsUnbonding":
			z.IsUnbonding, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "IsUnbonding")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Validator) Msgsize() (s int) {
	s = 1 + 8 + msgp.ArrayHeaderSize + (20 * (msgp.ByteSize)) + 7 + msgp.ArrayHeaderSize + (32 * (msgp.ByteSize)) + 9 + msgp.ArrayHeaderSize + (20 * (msgp.ByteSize)) + 12 + msgp.Int64Size + 13 + msgp.StringPrefixSize + len(z.Introduction) + 12 + msgp.ArrayHeaderSize + (32 * (msgp.ByteSize)) + 12 + msgp.BoolSize
	return
}
